spring.application.name=Java-SLF4J

#logging.level.root = INFO

#logging.level.com.dhyana.javaslf4j.controller = INFO
#logging.level.com.dhyana.javaslf4j.service = DEBUG

#logging.file.name = logs/app.log
#logging.pattern.file = %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} -%msg%n

#logging.pattern.console = %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} -%msg%n